name: company
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  flutter_svg:
  fluttertoast:
  go_router:
  flutter_screenutil: ^5.8.1
  equatable:
  flutter_bloc:
  bloc:
  get_it:
  carousel_slider:
  intl:
  shared_preferences:
  smooth_page_indicator:
  shimmer:
  timeline_tile:
  http:


  #fireBase
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_core:
  firebase_messaging:
  firebase_admin: ^0.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash:

flutter_native_splash:
  android: true
  ios: true
  color: "#6891F9"
  fullscreen: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Janna
      fonts:
        - asset: assets/fonts/Janna.ttf